# Generated by Django 4.0.10 on 2024-11-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0035_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='appointmentURL',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='emergencyURL',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='title',
            field=models.CharField(default='', max_length=180),
        ),
    ]
