# Generated by Django 4.0.10 on 2023-05-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designtemplates', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
